import { Inter } from 'next/font/google'
import PageHeroSection from '@/components/organisms/page-hero-section'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'The Kings Men',
  description: 'Generated by create next app',
}

export default function DeepLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <div>
      <PageHeroSection />
      {children}
    </div>
  )
}
