import { Inter } from 'next/font/google'
import { ServerThemeProvider } from 'next-themes'
import TopNavigation from '@/components/organisms/top-navigation'
import ThemerProvider from '@/components/providers'
import FooterSection from '@/components/organisms/footer-section'
import './globals.css'
// import '@radix-ui/themes/styles.css'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'The Kings Men',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <ServerThemeProvider enableSystem={true} defaultTheme="light">
      <html lang="en">
        <body suppressHydrationWarning={true} className={`${inter.className}`}>
          <ThemerProvider>
            <div id="app-root" className="app-default-layout overflow-x-hidden">
              <TopNavigation />
              {children}
              <FooterSection />
            </div>
          </ThemerProvider>
        </body>
      </html>
    </ServerThemeProvider>
  )
}
